name: ys-help

on:
  push:
    tags:
      - "ys-help@v*"

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: dist
      run: |
        cd packages/thc-www/__everkm 
        echo "${{ secrets.SSH_PRIVATE_KEY_LOCAL }}" > id_rsa_daobox
        chmod 0600 id_rsa_daobox
        pnpm i && make dist
        mv dist thc-www_next
        tar zcvf thc-www_next.tar.gz thc-www_next
        scp -o StrictHostKeyChecking=no -i id_rsa_daobox -P 11022 thc-www_next.tar.gz root@y5.everkm.com:/data/www/
        ssh -o StrictHostKeyChecking=no -i id_rsa_daobox -p 11022 root@y5.everkm.com <<EOF
          cd /data/www/
          tar zxvf thc-www_next.tar.gz
          rsync \
            --recursive \
            --verbose \
            --checksum \
            --delete \
            --compress \
            --links \
            --delete-after \
            --exclude=*.sh \
            ./thc-www_next/youlog/ \
            ./thc-www/youlog/
          rm -rf thc-www_next*
        EOF

    - name: push search index
      run: |
        cd packages/thc-www/__everkm
        pnpm i
        export ALGOLIA_APP_ID="${{ secrets.ALGOLIA_APP_ID }}"
        export ALGOLIA_API_KEY="${{ secrets.ALGOLIA_API_KEY }}"
        ./node_modules/.bin/ekmp-algolia --index-name tehaochi reset --languages zh --languages en --channel youlog --site tehaochi.cn
        ./node_modules/.bin/ekmp-algolia --index-name tehaochi walk --url-base https://tehaochi.cn/youlog/ --body-selector "#article-main" --channel youlog --site tehaochi.cn --dir thc-www_next/youlog

