name: ys-help

on:
  push:
    tags:
      - "ys-help@v*"

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: dist
      run: |
        # 准备 .ssh 目录
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

        # 配置 ssh 私钥
        echo "${{ secrets.SSH_KEY_DEPLOY_ED25519 }}" > ~/.ssh/id_rsa_daobox && chmod 600 ~/.ssh/id_rsa_daobox
        export QINIU_ACCESS_KEY=${{ secrets.QINIU_ACCESS_KEY }}
        export QINIU_SECRET_KEY=${{ secrets.QINIU_SECRET_KEY }}

        # 配置 known_hosts
        touch ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        echo "${{ secrets.Y7_EVERKM_COM_HOST_KEY }}" >> ~/.ssh/known_hosts

        
        # 安装依赖 并生成静态文件
        cd help/__everkm 
        pnpm i && make dist

        # 上传静态文件
        rsync \
          -e "ssh -i ~/.ssh/id_rsa_daobox -p 11022" \
          --recursive \
          --verbose \
          --checksum \
          --delete \
          --compress \
          --links \
          --delete-after \
          --exclude=*.sh \
          ./dist/. \
          root@y7.everkm.com:/data/www/help.yousha.top-next/

        # 同步静态文件至生产目录
        ssh -i ~/.ssh/id_rsa_daobox -p 11022 root@y7.everkm.com <<EOF
          cd /data/www/
          rsync \
            --recursive \
            --verbose \
            --checksum \
            --delete \
            --links \
            --delete-after \
            --exclude=*.sh \
            ./help.yousha.top-next/ \
            ./help.yousha.top/
        EOF

    - name: push search index
      run: |
        cd help/__everkm
        pnpm i
        export ALGOLIA_APP_ID="${{ secrets.ALGOLIA_APP_ID }}"
        export ALGOLIA_API_KEY="${{ secrets.ALGOLIA_API_KEY }}"
        ./node_modules/.bin/ekmp-algolia --index-name yousha reset --languages zh --languages en --channel help --site help.yousha.top
        ./node_modules/.bin/ekmp-algolia --index-name yousha walk --url-base https://help.yousha.top/ --body-selector "#article-main" --channel help --site help.yousha.top --dir dist/

